<?php

/**
 * PluginProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }
    
    /**
     * Return the query to sort categories
     * 
     * @return Doctrine_Query
     */
    public function addSortedCategory(Doctrine_Query $query)
    {
    	return $query->orderBy($query->getRootAlias().'.lft');
    }
    
	/**
	 * Return the query to fetch all roots
	 * 
	 * @return Doctrine_Query
	 */
	public function addFetchRootsInQuery(Doctrine_Query $query)
	{
		$q = $this->getTree()->getBaseQuery();
		$q = $q->addWhere($q->getRootAlias().'.level = ?', 1);
        
        return $this->addSortedCategory($q);
	}
	
	/**
	 * Return all categories sorted except root
	 * 
	 * @return Doctrine_Collection
	 */
	public function getAllCategoriesExceptRoot()
	{
		$q = $this->addSortedCategory($this->getTree()->getBaseQuery());
		$q->andWhere($q->getRootAlias().'.lft <> ?', 1);
		
		return $q->execute();
	}
}