<?php

/**
 * PluginProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProduct extends BaseProduct
{
	public function getMainImage()
	{
		return ProductImageTable::getInstance()->getFirstProductImage($this->getId());
	}
	
	public function getImagesInOrder()
	{
		return ProductImageTable::getInstance()->getProductImagesInOrder($this->getId());
	}
	
	public function getCategorySlug()
	{
		return $this->category->getSlug();
	}
}