<?php

/**
 * PluginProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }
    
	/**
	 * Return the query to fetch all roots
	 * 
	 * @return Doctrine_Query
	 */
	public function addFetchRootsInQuery(Doctrine_Query $query)
	{
		$tree = $this->getTree();
		$q = $tree->getBaseQuery();
        $q = $q->addWhere($q->getRootAlias().'.level = ?', 1)
          ->orderBy($q->getRootAlias().'.lft'); 
        
        return $q;
	}
}