<?php

/**
 * PluginProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTable extends Doctrine_Table
{
	/**
	 * @return Doctrine_Query
	 */
	public function getFeaturedProductQuery()
	{
		return $this->createQuery('p')
			->orderBy('p.is_featured DESC');
	}
}