<?php

/**
 * PluginProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProduct extends BaseProduct
{
	public function getImageFolder()
	{
	   return 'products';	
	}
	
    public function getImageWithPath($type = 'original')
    {
    	$image = $this->getImageFolder()."/";
    	if($type != 'original')
    	{
    		$image .= $type."/";
    	}
    	
    	$image .= ($this->getImageName())?$this->getImageName():'no-image.jpg';
    	
    	return sfContext::getInstance()->getRequest()->getRelativeUrlRoot().'/uploads/'.$image;
    }
    
    /**
     * Deletes all files
     * 
     * @param $mainDirectory
     */
    public function deleteAllImages($mainDirectory)
    {
    	foreach(sfConfig::get('app_ddOnlineStore_images') as $key=>$imagesType)
    	{
            if ($mainDirectory && is_file($file = $mainDirectory.'/'.$key.'/'.$this->getImageName()))
            {
                unlink($file);
            }
    	}
    }
}