<?php

/**
 * PluginProductColorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductColorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductColorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductColor');
    }
}