generator:
  class:                   sfDoctrineGenerator
  param:
    model_class:           ProductImage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_store_admin_product_image
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        image_name:        { label: "Image" }
        image_thumb:       { label: "Image" }
      
      list:
        title:             Product images list
        display:           [ _image_thumb ]
        sort:              [ position, asc ]
        max_per_page:      100
        object_actions:
          moveUp:          { label: " ", action: "moveUp" }
          moveDown:        { label: " ", action: "moveDown" }
          _edit:           ~
          _delete:         ~
        
      filter:
        display:           [ product_id ]
        
      form:
        display:
          Datos:           [ product_id, image_name ]
        
      edit:
        title:             Edit product image
        
      new: 
        title:             New product image