all:
  sfJqueryTree:
    route_back:       online_store_admin_category
    route_edit:       online_store_admin_category_edit
  
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    mime_type:
      auto_detect: true
      
  sfDoctrineJCroppablePlugin:
    models:
      ProductImage:
        directory:    products
        images:
          image_file:
            padding:    { percent: 0, color: "#ffffff" }
            ratio:      1
            sizes:
              thumb:    { width: 140, height: 102 }
              detail:   { width: 417, height: 321 }