online_store_admin_category:
  class:                  sfDoctrineRouteCollection
  options:
    model:                ProductCategory
    module:               ddOnlineStoreAdminCategory
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

online_store_admin_category_manage_tree:
  url:                    /category/:id/manageTree
  class:                  sfDoctrineRoute
  options:                { model: ProductCategory, type: object }
  param:                  { module: ddOnlineStoreAdminCategory, action: manageTree }
  requirements:
    id: \d+
    sf_method: [get]