generator:
  class:                   sfDoctrineGenerator
  param:
    model_class:           Product
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_store_admin_product
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  
        manage_images:     { label: "Images" }
        capacity:          { help: "Fill this field in MB" }
      
      list:    
        title:             "Products list"
        display:           [ category, name, _capacity, _price, _manage_images, is_available, is_featured, created_at ]
        sort:              [ created_at, desc ]
          
      filter:
        display:           [ category_id, name, created_at, is_available, is_featured ]
        
      form:    
        display:
          Main data:       [ category_id, name, subname, description, price ]
          Extra data:      [ capacity, specifications, is_available, is_featured ]
          
      edit:    
        title:             "Edit '%%name%%' product"
        
      new:     
        title:             "New product"