generator:
  class:                   sfDoctrineGenerator
  param:
    model_class:           Product
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_store_admin_product
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  
        image_name:        { label: "Image" }
      
      list:    
        title:             "Products list"
        display:           [ category, name, price, _image, created_at ]
        sort:              [ created_at, desc ]
          
      filter:
        display:           [ category_id, name, created_at ]
        
      form:    
        display:
          Main Data:       [ category_id, name, description, price, is_available ]
          Images:          [ image_name ]
          
      edit:    
        title:             "Edit '%%name%%' product"
        
      new:     
        title:             "New product"