generator:
  class:                   sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_store_admin_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title:             "Product Categories list"
        display:           [ name ]
      filter:
        class:             false
      form:    ~
      edit:    ~
      new:     ~
