generator:
  class:                   sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_store_admin_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:    
        title:             "Product Categories list"
        display:           [ name ]
        table_method:      addFetchRootsInQuery
        object_actions:
          _edit:           ~
          manage_tree:     
            label:         "Manage tree"
            params:        { class: "manage_tree" }
            action:        "manageTree"
          _delete:         ~
          
      filter:
        class:             false
        
      form:    ~
      edit:    ~
      new:     ~
