all:
  stylesheets:
    - /ddOnlineStorePlugin/css/screen.css
    
indexSuccess:
  javascripts:
    - /sfJqueryReloadedPlugin/js/jquery-1.3.2.min.js
    - /ddOnlineStorePlugin/js/jquery.tablednd_0_5.js