<?php

/**
 * ddValidatorColorPicker validates the value generated by ddWidgetFormColorPicker
 *
 * @package    symfony
 * @subpackage validator
 * @author     Diego D'amico <songecko@gmail.com>
 */

class ddValidatorColorPicker extends sfValidatorBase
{
  /**
   * @see sfValidatorBase
   */
  protected function doClean($value)
  {
    if (!preg_match('/^(?:(?:[a-f\d]{3}){1,2})$/i', $value)) {
      throw new sfValidatorError($this, 'invalid');
    }

    return $value;
  }
}
